#!/usr/bin/env python3
"""Analyze a model and print the information needed to design motions:

- parameter list from cdi3.json (IDs and display names)
- safe value range per parameter, observed across the existing motions
- parameters driven by physics (physics3.json outputs) — animating them
  directly gets overwritten, so they must be avoided
- base pose estimated from the first frame of the existing motions

Usage: python3 tools/analyze_model.py [runtime dir]
(without an argument, the model registered in model.config.json is used)
"""
import collections
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def resolve_runtime():
    if len(sys.argv) > 1:
        return sys.argv[1]
    cfg_path = os.path.join(ROOT, "model.config.json")
    if not os.path.exists(cfg_path):
        sys.exit("ERROR: model.config.json not found. Run python3 tools/setup_model.py first.")
    cfg = json.load(open(cfg_path))
    return os.path.join(ROOT, os.path.dirname(cfg["model3"]))


RUNTIME = resolve_runtime()


def find_one(pattern):
    files = glob.glob(os.path.join(RUNTIME, pattern))
    return files[0] if files else None


def curve_values(curve):
    """Return the (time, value) keyframes of a curve."""
    seg = curve["Segments"]
    pts = [(seg[0], seg[1])]
    i = 2
    while i < len(seg):
        if seg[i] == 1:  # bezier
            pts.append((seg[i + 5], seg[i + 6]))
            i += 7
        else:  # linear / stepped / inverse-stepped
            pts.append((seg[i + 1], seg[i + 2]))
            i += 3
    return pts


def main():
    cdi = find_one("*.cdi3.json")
    physics = find_one("*.physics3.json")
    # Motion folder names vary between models (motion/, motions/, ...),
    # so search recursively instead of assuming a directory name
    motions = sorted(glob.glob(os.path.join(RUNTIME, "**", "*.motion3.json"), recursive=True))

    # Exclude motions generated by this repo (the Action group): using our own
    # output as the reference would let value ranges drift over time
    model3 = find_one("*.model3.json")
    if model3:
        generated = {
            os.path.normpath(os.path.join(RUNTIME, e["File"]))
            for e in json.load(open(model3))["FileReferences"]["Motions"].get("Action", [])
        }
        motions = [f for f in motions if os.path.normpath(f) not in generated]

    names = {}
    if cdi:
        for p in json.load(open(cdi))["Parameters"]:
            names[p["Id"]] = p["Name"]

    physics_outputs = set()
    if physics:
        for s in json.load(open(physics))["PhysicsSettings"]:
            for o in s["Output"]:
                physics_outputs.add(o["Destination"]["Id"])

    stats = collections.defaultdict(lambda: [float("inf"), float("-inf"), 0])
    first_vals = collections.defaultdict(collections.Counter)
    for f in motions:
        d = json.load(open(f))
        for c in d["Curves"]:
            if c["Target"] != "Parameter":
                continue
            pts = curve_values(c)
            s = stats[c["Id"]]
            vals = [v for _, v in pts]
            s[0] = min(s[0], min(vals))
            s[1] = max(s[1], max(vals))
            s[2] += 1
            first_vals[c["Id"]][round(pts[0][1], 2)] += 1

    print(f"# runtime: {RUNTIME}")
    print(f"# aggregated from {len(motions)} existing motions\n")
    header = f"{'ParamId':32s} {'min':>8s} {'max':>8s} {'base(est)':>10s}  physics  display name"
    print(header)
    print("-" * len(header))
    for pid in sorted(set(names) | set(stats)):
        if pid in stats:
            mn, mx, _ = stats[pid]
            base = first_vals[pid].most_common(1)[0][0]
            rng = f"{mn:8.2f} {mx:8.2f} {base:10.2f}"
        else:
            rng = f"{'-':>8s} {'-':>8s} {'-':>10s}"
        phys = "  ★phys  " if pid in physics_outputs else "         "
        print(f"{pid:32s} {rng} {phys} {names.get(pid, '')}")
    print("\n★phys = destination of a physics3.json output. Never animate these "
          "directly (move the head/body angles and they sway naturally).")


if __name__ == "__main__":
    main()
