#!/usr/bin/env python3
"""Motion generation engine: build .motion3.json files from the definitions in
motion-defs/<model>.py and register them into the "Action" group of
model3.json (idempotent).

This file is a model-agnostic engine and should not need editing. Add or
tweak motions in motion-defs/<model>.py (the per-model definition file):

  - the target model is resolved from model.config.json
    (generated by tools/setup_model.py)
  - the definition file name is the model3.json file name without the
    extension (e.g. mao_pro.model3.json -> motion-defs/mao_pro.py)
  - see the bundled sample motion-defs/hiyori_pro_t11.py for the format
    (define(curve, motion) returns (MOTIONS, MANIFEST))
  - definitions are per-model workspace artifacts and, like models/, are
    git-ignored (only the bundled sample is tracked); keep one deliberately
    with `git add -f`

Output format:
  - curves are flat-tangent beziers with control points at 1/3 spacing,
    matching Cubism Editor's default ease-in/out
  - Meta counts (CurveCount / TotalSegmentCount / TotalPointCount) are
    computed from the actual data, never by hand
  - parameter IDs missing from the model's cdi3.json are reported as errors

Usage: python3 tools/gen_motions.py [runtime dir]
Always follow with: python3 tools/validate_motions.py
"""
import glob
import importlib.util
import json
import os
import sys

FPS = 30.0
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GROUP = "Action"  # replace only this group; never touch the existing ones
DEFS_DIR = os.path.join(ROOT, "motion-defs")


def resolve_runtime():
    if len(sys.argv) > 1:
        return sys.argv[1]
    cfg_path = os.path.join(ROOT, "model.config.json")
    if not os.path.exists(cfg_path):
        sys.exit("ERROR: model.config.json not found. Run python3 tools/setup_model.py first.")
    cfg = json.load(open(cfg_path))
    return os.path.join(ROOT, os.path.dirname(cfg["model3"]))


def snap(t):
    """Snap a time to the 30fps grid, matching editor-authored motions."""
    return round(round(t * FPS) / FPS, 3)


def curve(pid, keys):
    """keys: [(time, value), ...] -> bezier curve with flat tangents."""
    keys = [(snap(t), round(v, 3)) for t, v in keys]
    seg = [keys[0][0], keys[0][1]]
    for (t0, v0), (t1, v1) in zip(keys, keys[1:]):
        dt = (t1 - t0) / 3.0
        seg += [1, round(t0 + dt, 3), v0, round(t1 - dt, 3), v1, t1, v1]
    return {"Target": "Parameter", "Id": pid, "Segments": seg}


def motion(duration, curves):
    duration = snap(duration)
    total_segments = 0
    total_points = 0
    for c in curves:
        seg = c["Segments"]
        total_points += 1  # first keyframe
        i = 2
        while i < len(seg):
            total_segments += 1
            if seg[i] == 1:  # bezier: 2 control points + 1 end point
                total_points += 3
                i += 7
            else:  # linear / stepped / inverse-stepped: 1 end point
                total_points += 1
                i += 3
    return {
        "Version": 3,
        "Meta": {
            "Duration": duration,
            "Fps": FPS,
            "Loop": False,  # actions are one-shot, unlike looping idles
            "AreBeziersRestricted": True,
            "CurveCount": len(curves),
            "TotalSegmentCount": total_segments,
            "TotalPointCount": total_points,
            "UserDataCount": 0,
            "TotalUserDataSize": 0,
        },
        "Curves": curves,
    }


def load_definitions(stem):
    def_path = os.path.join(DEFS_DIR, f"{stem}.py")
    if not os.path.exists(def_path):
        sys.exit(f"ERROR: no motion definitions for this model: {def_path}\n"
                 f"Create it using the bundled sample motion-defs/hiyori_pro_t11.py as a reference\n"
                 f"(inspect the available parameters with python3 tools/analyze_model.py).")
    spec = importlib.util.spec_from_file_location(f"motion_defs_{stem}", def_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    motions, manifest = mod.define(curve, motion)
    if set(n for n, *_ in manifest) != set(motions):
        sys.exit(f"ERROR: MANIFEST and MOTIONS keys do not match in {def_path}.")
    return motions, manifest, def_path


def motion_reference(name, display_name, fade_in, fade_out):
    """Build a model3.json motion reference with optional localized names."""
    if isinstance(display_name, dict):
        default_name = display_name.get("en", next(iter(display_name.values())))
    else:
        default_name = display_name
    entry = {
        "File": f"motion/{name}.motion3.json",
        "Name": default_name,
        "FadeInTime": fade_in,
        "FadeOutTime": fade_out,
    }
    if isinstance(display_name, dict):
        entry["Names"] = display_name
    return entry


def main():
    runtime = resolve_runtime()

    model3_files = glob.glob(os.path.join(runtime, "*.model3.json"))
    if len(model3_files) != 1:
        sys.exit(f"ERROR: found {len(model3_files)} model3.json files in {runtime}; exactly one is required.")
    model3_path = model3_files[0]
    stem = os.path.basename(model3_path).replace(".model3.json", "")

    motions, manifest, def_path = load_definitions(stem)
    print(f"definitions: {def_path} ({len(motions)} motions)")

    # Verify every referenced parameter exists in the model (when cdi3.json is present)
    cdi_files = glob.glob(os.path.join(runtime, "*.cdi3.json"))
    if cdi_files:
        available = {p["Id"] for p in json.load(open(cdi_files[0]))["Parameters"]}
        missing = sorted({
            c["Id"] for m in motions.values() for c in m["Curves"]
            if c["Target"] == "Parameter" and c["Id"] not in available
        })
        if missing:
            sys.exit(f"ERROR: the following parameters do not exist in this model.\n"
                     f"Rewrite {def_path} for this model "
                     f"(check the available parameters with tools/analyze_model.py):\n  "
                     + "\n  ".join(missing))

    motion_dir = os.path.join(runtime, "motion")
    os.makedirs(motion_dir, exist_ok=True)
    for name, data in motions.items():
        path = os.path.join(motion_dir, f"{name}.motion3.json")
        with open(path, "w") as fh:
            json.dump(data, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        m = data["Meta"]
        print(f"wrote {path}: dur={m['Duration']} curves={m['CurveCount']} "
              f"segs={m['TotalSegmentCount']} pts={m['TotalPointCount']}")

    # Replace the whole Action group in model3.json (other groups untouched; idempotent)
    model3 = json.load(open(model3_path))
    # setdefault so this also works on models that ship without any motions
    model3.setdefault("FileReferences", {}).setdefault("Motions", {})[GROUP] = [
        motion_reference(name, disp, fin, fout)
        for name, disp, fin, fout in manifest
    ]
    with open(model3_path, "w") as fh:
        json.dump(model3, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    print(f"registered {len(manifest)} motions to {model3_path} [{GROUP}]")


if __name__ == "__main__":
    main()
